# Generated by Django 2.1.7 on 2019-04-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('学院名称', models.CharField(max_length=100, verbose_name='学院名称')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='编号')),
                ('name', models.CharField(max_length=500, verbose_name='仪器名称')),
                ('model_number', models.CharField(max_length=500, verbose_name='仪器编号')),
                ('maker', models.CharField(max_length=500, verbose_name='厂家')),
                ('type', models.CharField(max_length=500, verbose_name='类别')),
                ('is_lend', models.BooleanField(default=False, verbose_name='是否出借')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='实验室名称')),
                ('关联学院', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department', verbose_name='关联学院')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Lab'),
        ),
    ]
