# Generated by Django 2.1.7 on 2019-04-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('text', models.TextField(max_length=1000, verbose_name='内容')),
                ('time', models.DateField(verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '申请',
                'verbose_name_plural': '申请',
            },
        ),
        migrations.CreateModel(
            name='ApplyInstrumentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Apply', verbose_name='申请')),
            ],
            options={
                'verbose_name': '申请对应仪器表',
                'verbose_name_plural': '申请对应仪器表',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='编号')),
                ('name', models.CharField(max_length=500, verbose_name='仪器名称')),
                ('model_number', models.CharField(max_length=500, verbose_name='仪器编号')),
                ('maker', models.CharField(max_length=500, verbose_name='厂家')),
                ('type', models.CharField(max_length=500, verbose_name='类别')),
                ('is_lend', models.BooleanField(default=False, verbose_name='是否出借')),
            ],
            options={
                'verbose_name': '实验仪器',
                'verbose_name_plural': '实验仪器',
                'get_latest_by': 'number',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='实验室名称')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department', verbose_name='关联学院')),
            ],
            options={
                'verbose_name': '实验室',
                'verbose_name_plural': '实验室',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Lab', verbose_name='所属实验室'),
        ),
        migrations.AddField(
            model_name='applyinstrumentlist',
            name='Instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Instrument', verbose_name='仪器'),
        ),
        migrations.AddField(
            model_name='apply',
            name='ApplyInstrumentList_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ApplyInstrumentList', verbose_name='申请'),
        ),
    ]
