# Generated by Django 2.1.7 on 2019-08-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='weid',
            field=models.CharField(default='', max_length=30, verbose_name='微信id'),
        ),
    ]
