# Generated by Django 2.1.7 on 2019-10-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('导入excel', models.FileField(upload_to='excel/%Y/%m/%d/', verbose_name='导入Excel')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Lab', verbose_name='所属实验室')),
            ],
            options={
                'verbose_name': 'excel导入',
                'verbose_name_plural': 'excel导入',
            },
        ),
        migrations.RemoveField(
            model_name='excelimporter',
            name='lab_id',
        ),
        migrations.DeleteModel(
            name='ExcelImporter',
        ),
    ]
