# Generated by Django 2.1.7 on 2019-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='formId',
            field=models.CharField(default='无', max_length=50, verbose_name='表单id'),
        ),
        migrations.AddField(
            model_name='apply',
            name='openId',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='用户微信的openId'),
        ),
    ]
