# Generated by Django 2.1.7 on 2019-04-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '学院', 'verbose_name_plural': '学院'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'get_latest_by': 'number', 'verbose_name': '实验仪器', 'verbose_name_plural': '实验仪器'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': '实验室', 'verbose_name_plural': '实验室'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='学院名称',
            new_name='name',
        ),
    ]
