# Generated by Django 2.1.7 on 2019-04-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='ApplyInstrumentList_id',
        ),
    ]
