# Generated by Django 2.1.7 on 2019-04-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190401_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='关联学院',
            new_name='department_id',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Lab', verbose_name='所属实验室'),
        ),
    ]
