# Generated by Django 2.1.7 on 2019-10-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191029_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelreader',
            name='lab_id',
        ),
        migrations.DeleteModel(
            name='ExcelReader',
        ),
    ]
