# Generated by Django 2.1.7 on 2019-08-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190826_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='openId',
            field=models.CharField(default='None', max_length=32, verbose_name='用户微信的openId'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='statu',
            field=models.SmallIntegerField(choices=[(1, '通过'), (-1, '未通过'), (0, '未处理'), (2, '已归还')], default=0, verbose_name='状态'),
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='belong_lab',
        ),
        migrations.AddField(
            model_name='myuser',
            name='belong_lab',
            field=models.ManyToManyField(blank=True, null=True, related_name='belongLab', to='user.Lab', verbose_name='所属实验室'),
        ),
    ]
