# Generated by Django 2.1.7 on 2019-04-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190410_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='number',
        ),
    ]
