# Generated by Django 2.1.7 on 2019-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191029_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='describe',
            field=models.CharField(default='', max_length=500, verbose_name='仪器描述'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='model_type',
            field=models.CharField(default='', max_length=200, verbose_name='仪器型号'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='maker',
            field=models.CharField(default='', max_length=500, verbose_name='厂家'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='model_number',
            field=models.CharField(default='', max_length=500, verbose_name='仪器编号'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='仪器名称'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.CharField(default='', max_length=500, verbose_name='类别'),
        ),
    ]
